### ISSUE TITLE
Update tests for MOI update

### ISSUE THREAD

**Issue by ericphanson** [ericphanson/SDPAFamily.jl#27]
See eg https://travis-ci.com/ericphanson/SDPAFamily.jl/jobs/244828876

**Comment by blegat** [comment]
Up, it is the last (CI-testable) solver failing with MOI master: https://travis-ci.com/blegat/SolverTests

**Comment by ericphanson** [comment]
Ah sorry, I should’ve fixed this before adding it to the JuMP docs to be tested. I’ll fix it tomorrow, I think we always only use one thread so I can just add the attribute to say that (but I should check to be sure).

**Comment by blegat** [comment]
> Ah sorry, I should’ve fixed this before adding it to the JuMP docs to be tested.

No worry, I just make sure to notify solvers failing tests before tagging a new path release of MOI.

**Comment by ericphanson** [comment]
Closed by https://github.com/ericphanson/SDPAFamily.jl/commit/958d9cc8463c10c45e70da72ebee88940a7c48a8
