### ISSUE TITLE
Error when `using SDPAFamily`

### ISSUE THREAD

**Issue by ericphanson** [ericphanson/SDPAFamily.jl#29]
Sometimes I get this error when calling `using SDPAFamily`:
```
ERROR: could not load library "/Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/sys.dylib"
dlopen(/Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/sys.dylib, 6): Symbol not found: _jl_apply_2va
  Referenced from: /Applications/Julia-1.0.app/Contents/Resources/julia/lib/julia/sys.dylib
  Expected in: /Applications/Julia-1.3.app/Contents/Resources/julia/bin/../lib/libjulia.dylib
 in /Applications/Julia-1.0.app/Contents/Resources/julia/lib/julia/sys.dylib
```
I think it comes from using SDPAFamily from different Julia versions, and needing to rebuild the package. I'm not quite sure how to fix it; I think one easy fix might just be to remove the plain-SDPA functionality and only support the high-precision variants, since then we don't need to link against anything.

**Comment by ericphanson** [comment]
This is because of eg
```

    libpaths = split(get(ENV, "DYLD_LIBRARY_PATH", ""), ":")
    if !("/Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia" in libpaths)
        push!(libpaths, "/Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia")
    end
```
being present in the `deps.jl` file generated by BinaryProvider. Not sure why it's doing Julia-version-specific things, but it can be worked around by re-`build`ing the package when switching Julia versins.

**Comment by ericphanson** [comment]
I think this will be solved by switching SDPA to a JLL package when https://github.com/JuliaPackaging/Yggdrasil/pull/804 is finished.

**Comment by ViralBShah** [comment]
Now in JuliaPackaging/Yggdrasil#1478. It would be great if folks from here can help on that PR. I believe we should be fairly close.

**Comment by ericphanson** [comment]
That’s awesome! I have to say, I really don’t know the Cxxwrap internals at all, I just copied them from https://github.com/jump-dev/SDPA.jl (I think @blegat has done a lot of work for that package, so he might know better)

**Comment by ViralBShah** [comment]
We definitely need updates on the cxxwrap. See comments in the Yggdrasil PR.

**Comment by ViralBShah** [comment]
This is merged now. Can we try it out. Do see the comments in the Yggdrasil PR about the gfortran issue- but it should hopefully just work.
